// Mapping cuisine types.
export const cuisineTypes = {
  american: 'american',
  asian: 'asian',
  british: 'british',
  caribbean: 'caribbean',
  'central-europe': 'central europe',
  chinese: 'chinese',
  'eastern-europe': 'eastern europe',
  french: 'french',
  greek: 'greek',
  indian: 'indian',
  italian: 'italian',
  japanese: 'japanese',
  korean: 'korean',
  kosher: 'kosher',
  mediterranean: 'mediterranean',
  mexican: 'mexican',
  'middle-eastern': 'middle eastern',
  nordic: 'nordic',
  'south-american': 'south american',
  'south-east asian': 'south east asian',
  world: 'world',
} as const;

// Mapping diet labels.
export const dietLabels = {
  Balanced: 'balanced',
  'High-Fiber': 'high-fiber',
  'High-Protein': 'high-protein',
  'Low-Carb': 'low-carb',
  'Low-Fat': 'low-fat',
  'Low-Sodium': 'low-sodium',
} as const;

// Mapping dish types.
export const dishTypes = {
  'alcohol-cocktail': 'alcohol cocktail',
  'biscuits-cookies': 'biscuits and cookies',
  bread: 'bread',
  cereals: 'cereals',
  'condiments-sauces': 'condiments and sauces',
  desserts: 'desserts',
  drinks: 'drinks',
  egg: 'egg',
  'ice-cream-custard': 'ice cream and custard',
  main: 'main course',
  pancake: 'pancake',
  pasta: 'pasta',
  pastry: 'pastry',
  'pies-tarts': 'pies and tarts',
  pizza: 'pizza',
  preps: 'preps',
  preserve: 'preserve',
  salad: 'salad',
  sandwiches: 'sandwiches',
  seafood: 'seafood',
  side: 'side dish',
  soup: 'soup',
  'special-occasion': 'special occasions',
  starter: 'starter',
  sweets: 'sweets',
} as const;

// Mapping health labels.
export const healthLabels = {
  'Alcohol-Cocktail': 'alcohol-cocktail',
  'Alcohol-Free': 'alcohol-free',
  'Celery-Free': 'celery-free',
  'Crustacean-Free': 'crustacean-free',
  'Dairy-Free': 'dairy-free',
  DASH: 'DASH',
  'Egg-Free': 'egg-free',
  'Fish-Free': 'fish-free',
  'FODMAP-Free': 'fodmap-free',
  'Gluten-Free': 'gluten-free',
  'Immuno-Supportive': 'immuno-supportive',
  'Keto-Friendly': 'keto-friendly',
  'Kidney-Friendly': 'kidney-friendly',
  Kosher: 'kosher',
  'Low Potassium': 'low-potassium',
  'Low Sugar': 'low-sugar',
  'Lupine-Free': 'lupine-free',
  Mediterranean: 'Mediterranean',
  'Mollusk-Free': 'mollusk-free',
  'Mustard-Free': 'mustard-free',
  'No oil added': 'No-oil-added',
  Paleo: 'paleo',
  'Peanut-Free': 'peanut-free',
  Pescatarian: 'pecatarian',
  'Pork-Free': 'pork-free',
  'Red-Meat-Free': 'red-meat-free',
  'Sesame-Free': 'sesame-free',
  'Shellfish-Free': 'shellfish-free',
  'Soy-Free': 'soy-free',
  'Sugar-Conscious': 'sugar-conscious',
  'Sulfite-Free': 'sulfite-free',
  'Tree-Nut-Free': 'tree-nut-free',
  Vegan: 'vegan',
  Vegetarian: 'vegetarian',
  'Wheat-Free': 'wheat-free',
} as const;

// Mapping meal types.
export const mealTypes = {
  breakfast: 'breakfast',
  brunch: 'brunch',
  'lunch-dinner': 'lunch/dinner',
  snack: 'snack',
  teatime: 'teatime',
} as const;

// Mapping nutrient types.
export const nutrients = {
  'SUGAR.added': 'Added sugar',
  CA: 'Calcium',
  'CHOCDF.net': 'Carbohydrate',
  CHOCDF: 'Carbohydrate, by difference',
  CHOLE: 'Cholesterol',
  ENERC_KCAL: 'Energy',
  FAMS: 'Fatty acids, total monounsaturated',
  FAPU: 'Fatty acids, total polyunsaturated',
  FASAT: 'Fatty acids, total saturated',
  FATRN: 'Fatty acids, total transcode',
  FIBTG: 'Fiber, total dietary',
  FOLDFE: 'Folate, DFE',
  FOLFD: 'Folate, food',
  FOLAC: 'Folic acid',
  FE: 'Iron, Fe',
  MG: 'Magnesium',
  NIA: 'Niacin',
  P: 'Phosphorus, P',
  K: 'Potassium, K',
  PROCNT: 'Protein',
  RIBF: 'Riboflavin',
  NA: 'Sodium, Na',
  'Sugar.alcohol': 'Sugar alcohols',
  SUGAR: 'Sugars',
  THIA: 'Thiamin',
  FAT: 'Total lipid (fat)',
  VITA_RAE: 'Vitamin A, RAE',
  VITB12: 'Vitamin B-12',
  VITB6A: 'Vitamin B-6',
  VITC: 'Vitamin C, total ascorbic acid',
  VITD: 'Vitamin D (D2 + D3)',
  TOCPHA: 'Vitamin E (alpha-tocopherol)',
  VITK1: 'Vitamin K (phylloquinone)',
  WATER: 'Water',
  ZN: 'Zinc',
} as const;
